### ISSUE TITLE
Failed tests do not output the Actual vs Expected result

### ISSUE THREAD

**Issue by Flave229** [dangmoody/Temper#18]
When tests fail, I am forced to debug the code to see the actual vs expected results. Ideally, this should automatically print out to the log.

**Comment by Flave229** [comment]
I can look at adding this :)

**Comment by dangmoody** [comment]
This makes sense to output for functions like `TEMPER_CHECK_EQUALS()` etc. but probably not for `TEMPER_CHECK_TRUE()` (since you expected `true`/`false` and got the opposite) so we will only be able to implement this for so many of those functions.

Still worth doing though.  This is a good idea.

**Comment by Mike430** [comment]
Hey all!

I just wanted to give this a nudge and share some thoughts as Dan and I were talking about getting a new release ready - the current plan is Good Friday (April 7th). As this is something you've raised, Dave, I felt it only appropriate you be brought up to speed and we get your thoughts on this.

Suppose the given test:
```C++
TEMPER_TEST( ComparingLogging, TEMPER_FLAG_SHOULD_RUN )
{
	int a = 7;
	int b = 8;
	TEMPER_CHECK_EQUAL(a, b);
	TEMPER_CHECK_EQUAL_M(a, b, "Expected (%d, %d) to match.", a, b);
}
```

This results in the following output:
```
TEST: "ComparingLogging"
FAILED: TEMPER_CHECK_EQUAL(a, b) at /home/mike/Source/Dangmoody/Temper/tests/automation_c/automation_c.c line 22.
FAILED: TEMPER_CHECK_EQUAL_M(a, b, ...) at /home/mike/Source/Dangmoody/Temper/tests/automation_c/automation_c.c line 23.
Expected (7, 8) to match.
TEST FAILED (23.885 microseconds)
```

The first error line is useless in helping here as it requires debugging, like you said, but the second one sounds like what we're aiming for. Dan and I had a chat about it and without getting into C++ templates we struggle to think of a way in which we could understand the types such that we can print effectively. As you can see we do a %d here but if we had floats we'd need a %f, for a double a %lf and a string a %s etc etc etc.

The conclusion Dan and I reached was that we could and are considering making it so that TEMPER_CHECK with _M modifiers for messages are depricated and no longer available, forcing people for every check to actually explain what the hell went wrong which would inelegantly sidestep the issue as the burden is still on the user to go and print everything nicely.

Something that may help us get around this problem is if we could find an implementation fmt (formatted printing where you just specify the variable index and then it just works out the rest) for C99, though this wouldn't help if it came to trying to do a comparison on two objects, this would bring us effectively back to square one AFAIK.

What are your thoughts?
Will you have a chance to look at this before Good Friday?
It's cool if you're busy between now and then, if that's the case then I could probably try and pick this up.

**Comment by Mike430** [comment]
Had a longer think about this. It'd be nice to handle this but there is no magic bullet solution for us to do this for you. Taking the example TEMPER_CHECK_EQUALS - it can compare the output of two values, two functions or two expressions (and whatever else you want to throw at it - preprocessors). Under all these circumstances there is no way for us to dissect what any and every value may end up being. Same even goes for TEMPER_CHECK_TRUE and all the others - in that case alone, given a boolean expression involving several variables and operators, how should we disect that?

We provide printf functionality for a reason, it is recommended you always add a log to talk about what you expect.

**Comment by Mike430** [comment]
Missed the close button - whoops :P
